### ISSUE TITLE
[Bug report] lexer.c

### ISSUE THREAD

**Issue by Jaekpark** [yeslee-v/42_minishell#25]
+ Bug occurred after rewriting `lexer.c` according to Norm V3
  + Function `lexer` does not recognize `quotation marks` when analyzing the command.
  + As a result, the `arg_line` variable on `t_syntax` structure does not contain valid data.

**Comment by yeslee-v** [comment]
다음 명령어 실행시, 달러 표시 이전까지만 파싱됩니다
```bash
echo "$PWD"
```
```bash
[lexical analysis]
cmd = echo "$PWD"
lex = ccccsD
------------------
[tokenizing]
token = echo, type = S, index = 0, st = 0, ed = 3, next = 0x128004120
token = ", type = S, index = 1, st = 5, ed = 5, next = 0x0
------------------
[parsing]
process no.0
next = 0x0
cmd = echo, arg = "
------------------
"
```

**Comment by Jaekpark** [comment]
> 다음 명령어 실행시, 달러 표시 이전까지만 파싱됩니다
> 
> ```shell
> echo "$PWD"
> ```
> 
> ```shell
> [lexical analysis]
> cmd = echo "$PWD"
> lex = ccccsD
> ------------------
> [tokenizing]
> token = echo, type = S, index = 0, st = 0, ed = 3, next = 0x128004120
> token = ", type = S, index = 1, st = 5, ed = 5, next = 0x0
> ------------------
> [parsing]
> process no.0
> next = 0x0
> cmd = echo, arg = "
> ------------------
> "
> ```

해당 이슈와 링크된 pull request 에서 디버깅된 사항입니다
