### ISSUE TITLE
New feature required

### ISSUE THREAD

**Issue by Jaekpark** [yeslee-v/42_minishell#43]
```bash
"echo" hi -> "[CMD]" [ARG]
echo "hi.      "   "     hi"
echo "hi""hi"
```

**Comment by yeslee-v** [comment]
Do not implement this case.

```bash
"echo" hi -> "[CMD]" [ARG]
````

In subject,
• ’ inhibit all interpretation of a sequence of characters.
• " inhibit all interpretation of a sequence of characters except for $.

**Comment by yeslee-v** [comment]
파싱 단계에서 cmd->args에 ""를 제외한 그대로 들어가게 구현함
