### ISSUE TITLE
[Bug report] builtin & memory

### ISSUE THREAD

**Issue by Jaekpark** [yeslee-v/42_minishell#75]
### echo

+ `echo $@# $^ $*` =>  달러 뒤에 특수문자 올경우 출력해줘야 하는데 출력 안됨.
+ `echo ""` `echo "$P_"` 처럼  t_cmd -> arg가 비어있을때 개행 출력이 안됨.
+ `echo - n hi`  처럼 - 다음 공백이 오고  n이 오면 옵션으로 인식하는 에러 
+ `echo '$PATH'` 로 들어오는 경우 환경변수를 출력함 ->  blt_echo 의 is_env에서 환경변수 값으로 변환해버림. 

### export

+ `export a==b` 처럼 '=' 가 두개 이상올 경우 'a=b'로 환경변수 추가됨  올바른 결과 -> 'a==b' -> 스플릿하는 과정에서 사라지는듯
+ `export =b` 나 ` export @=a' 처럼 환경변수로 등록할수 없는 문자나 문법이 입력 될경우 `bash: export: `=b(입력된 문자)': not a valid identifier` 에러메시지 출력후 에러 종료해야함 -> 현재는 환경변수에 `b=` `@=` 형태로 등록됨
+ `export a=b wefklwef` `export a=b c=d`  처럼 export에  arg가 **2개 이상 들어왔을때**  각각의 인자별로 처리해야함 즉,  a=b, c=d 처럼 별개로 등록되어야하지만
  현재 전자의 경우 a=b wefklwef 로 등록되고 후자는 a=b c로 등록 되어있음 ->  t_cmd의 arg로 처리해서 문제가 생기는거 같은데 args에 담긴 데이터 사용해서 각각의 인자별로 처리해야함 .
+ `export =` 입력시   seg fault

### unset

+ `unset` 도 위와 마찬가지로 `unset @` `unset @=a`  와 같은 형태로 환경변수에   적합하지 않은 문자나 문법으로 입력될경우 not a vaild identifier 출력해야함

### memory error

+ 빈 프롬포트 입력시 메모리 에러 -> num = is_blt 쪽(t_cmd -> char *cmd == NULL일때도 빌트인인지 확인해서  빈메모리 참조 에러

**Comment by yeslee-v** [comment]
memory error
proc->cmd가 아닌 proc 유무를 확인해야 함

**Comment by yeslee-v** [comment]
exit을 builtin 함수 안에 넣음
